version: '3.8'

services:
  code-executor:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
